# SPDX-FileCopyrightText: 2025-2026 Carlson Büth <code@cbueth.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: [push, pull_request]
    branch: [main, develop]

steps:
  - name: fmt
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: clippy
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features -- -D warnings -W clippy::cargo

  - name: doc
    image: rust:latest
    environment:
      RUSTDOCFLAGS: "--html-in-header katex-header.html"
    commands:
      - cargo doc --no-deps --all-features
      # Check if documentation builds without warnings
      - grep -q "warning" target/doc/infomeasure/index.html && exit 1 || true
