# SPDX-FileCopyrightText: 2025-2026 Carlson Büth <code@cbueth.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

workspace:
  base: /build
  path: .

when:
  - event: [push, pull_request]
    branch: [main, develop]
  - event: manual

matrix:
  RUST: [stable, beta]

steps:
  - name: fmt
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    commands:
      - cargo fmt --all -- --check

  - name: clippy
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    commands:
      - cargo clippy --all-targets --all-features -- -D warnings -W clippy::cargo

  - name: doc
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    environment:
      RUSTDOCFLAGS: "-D warnings --html-in-header katex-header.html"
    commands:
      - cargo doc --no-deps --all-features
