# SPDX-FileCopyrightText: 2025-2026 Carlson Büth <code@cbueth.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: [push, pull_request]
    branch: [main, develop]

matrix:
  RUST: [stable, beta]
  FEATURES: ["", fast_exp]


steps:
  - name: build
    image: rust
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      - rustup default ${RUST}
      - if [ -n "${FEATURES}" ]; then
          cargo build -j 4 --workspace --features ${FEATURES};
        else
          cargo build -j 4 --workspace;
        fi

  - name: test
    image: rust
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      # Install micromamba for Python validation
      - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      - mv bin/micromamba /usr/local/bin/
      - export MAMBA_ROOT_PREFIX=/opt/conda
      - eval "`micromamba shell hook`"
      # Create Python environment
      - micromamba create -f tests/validation_crate/environment.yml

      # Run tests with current feature set
      - if [ -n "${FEATURES}" ]; then
          cargo test -j 4 --workspace --features ${FEATURES};
        else
          cargo test -j 4 --workspace;
        fi
