# SPDX-FileCopyrightText: 2025-2026 Carlson Büth <code@cbueth.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

workspace:
  base: /build
  path: .

when:
  - event: [push, pull_request]
    branch: [main, develop]
    path:
      - Cargo.toml
      - Cargo.lock
      - src/**
      - tests/**
  - event: manual

matrix:
  RUST: [stable, beta]
  FEATURES: [""]  # fast_exp degrades the accuracy, making tests fail; not testing gpu on CI


steps:
  - name: build
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      - if [ -n "${FEATURES}" ]; then
          cargo build -j 4 --workspace --features ${FEATURES};
        else
          cargo build -j 4 --workspace;
        fi

  - name: test
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      - if [ -n "${FEATURES}" ]; then
          cargo test -j 4 --workspace --features ${FEATURES};
        else
          cargo test -j 4 --workspace;
        fi

  - name: doctest
    image: codeberg.org/cbueth/infomeasure-rs:${RUST}
    commands:
      - cargo test --doc
