# SPDX-FileCopyrightText: 2025-2026 Carlson Büth <code@cbueth.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: [push, pull_request]
    branch: [main, develop]

matrix:
  RUST: [stable, beta]
  FEATURES: [""]  # fast_exp degrades the accuracy, making tests fail; not testing gpu on CI


steps:
  - name: build
    image: rust
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      - rustup default ${RUST}
      - if [ -n "${FEATURES}" ]; then
          cargo build -j 4 --workspace --features ${FEATURES};
        else
          cargo build -j 4 --workspace;
        fi

  - name: test
    image: rust
    environment:
      FEATURES: ${FEATURES}
      RUST: ${RUST}
    commands:
      # Install uv for Python validation
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - source $HOME/.local/bin/env
      # Set up Python environment with uv
      - cd tests/validation_crate
      - uv venv
      - uv pip install -r requirements.txt
      - cd ../..

      # Run tests with current feature set
      - if [ -n "${FEATURES}" ]; then
          cargo test -j 4 --workspace --features ${FEATURES};
        else
          cargo test -j 4 --workspace;
        fi
